server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

logging:
  level:
    com:
      xry:
        product:
          mapper: debug

mybatis:
  type-aliases-package: com.xry.product.pojo
  mapper-locations: classpath:mappers/*.xml
  configuration:
    cache-enabled: true